#!/usr/bin/env python3
# =============================================================================
# gen_registry_rows.py -- generates and idempotently upserts new
# opticalproperties/ registry rows (+ their per-item tables) for the
# "catalog primitives" round: a beamsplitter-ratio family, pellicles, and
# reflective/absorptive neutral-density rows in coating/coatings.miecoat,
# plus an ND filter family and two spectral filter rows in
# filter/filters.miefilt.
#
# stdlib-only (python3). Deterministic: every value is derived from either
# the shipped bs_5050_vis_45 / longpass_600 tables or a closed-form formula
# below, so re-running this script produces byte-identical output --
# running it twice must leave `git diff` empty.
#
# Run:  python3 scripts/tools/gen_registry_rows.py   (from anywhere)
# =============================================================================
import csv
import io
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPT = ROOT / "opticalproperties"

COATINGS_CSV = OPT / "coating" / "coatings.miecoat"
COATING_TABLES = OPT / "coating" / "tables"
FILTERS_CSV = OPT / "filter" / "filters.miefilt"
FILTER_TABLES = OPT / "filter" / "tables"

GEN_TAG = "generated by scripts/tools/gen_registry_rows.py"

# All shipped registry/table files in this repo use CRLF line endings and
# csv.QUOTE_MINIMAL quoting (only fields containing a comma get quoted) --
# match that exactly so untouched rows round-trip byte-for-byte and new
# rows don't stand out.
CSV_KW = dict(lineterminator="\r\n")


def fmt(v):
    """Number formatting used in generated tables: up to 9 significant
    digits, shortest representation (matches the style of the shipped
    tables, e.g. '0.505176', '1.16e-05')."""
    return "%.9g" % float(v)


# ---------------------------------------------------------------------------
# generic CSV registry read/upsert
# ---------------------------------------------------------------------------
def read_registry(path):
    with open(path, newline="") as fh:
        reader = csv.DictReader(fh)
        fieldnames = reader.fieldnames
        rows = list(reader)
    return fieldnames, rows


def upsert_registry(path, new_rows):
    """new_rows: list of dicts keyed like the registry's fieldnames.
    Rows whose 'name' already exists are updated in place (preserving
    original position); unseen names are appended in the given order.
    Only rewrites the file if the resulting content differs."""
    fieldnames, rows = read_registry(path)
    by_name = {r["name"]: i for i, r in enumerate(rows)}
    for nr in new_rows:
        name = nr["name"]
        row = {c: nr.get(c, "") for c in fieldnames}
        if name in by_name:
            rows[by_name[name]] = row
        else:
            rows.append(row)
            by_name[name] = len(rows) - 1

    buf = io.StringIO()
    writer = csv.writer(buf, **CSV_KW)
    writer.writerow(fieldnames)
    for r in rows:
        writer.writerow([r[c] for c in fieldnames])
    new_content = buf.getvalue()

    old_content = _read_raw(path)
    if new_content != old_content:
        _write_raw(path, new_content)
        return True
    return False


def _read_raw(path):
    """Read a text file with newline='' (no universal-newline translation)
    -- needed on py3.10 where Path.read_text() lacks a newline= kwarg."""
    with open(path, "r", newline="") as fh:
        return fh.read()


def _write_raw(path, content):
    with open(path, "w", newline="") as fh:
        fh.write(content)


def write_table(path, header, rows):
    """rows: list of tuples of raw values (numbers or strings), same order
    as header. Writes CRLF, only touches the file if content changed."""
    buf = io.StringIO()
    writer = csv.writer(buf, **CSV_KW)
    writer.writerow(header)
    for r in rows:
        writer.writerow([v if isinstance(v, str) else fmt(v) for v in r])
    new_content = buf.getvalue()
    old_content = _read_raw(path) if path.exists() else None
    if new_content != old_content:
        _write_raw(path, new_content)
        return True
    return False


def read_table(path):
    with open(path, newline="") as fh:
        reader = csv.DictReader(fh)
        return list(reader)


# ---------------------------------------------------------------------------
# 1) beamsplitter ratio family, 45 deg AOI, same grid as bs_5050_vis_45
#
# Construction: at every wavelength row of bs_5050_vis_45, let
#   Ravg = (Rs+Rp)/2, Tavg = (Ts+Tp)/2, total = Ravg + Tavg  (== 0.98 here)
#   d0   = Rs - Rp        (== -(Ts - Tp) in the source table, verified below)
# For a target ratio (rR : rT) with rR+rT == 1:
#   Ravg' = rR * total ;  Tavg' = rT * total          -> Ravg'+Tavg' = total
#   d'    = d0 * 4*rR*rT                                (shrinks toward 0 at
#           extreme ratios, == d0 at 50:50, keeps every channel in [0,1])
#   Rs' = Ravg' + d'/2 ; Rp' = Ravg' - d'/2
#   Ts' = Tavg' - d'/2 ; Tp' = Tavg' + d'/2
# so Rs'+Ts' == Rp'+Tp' == total EXACTLY (same total insertion loss as the
# 5050 source, per wavelength) and Rs'/Rp' carries the same s/p-asymmetry
# "style" as the source, scaled to the new split.
# ---------------------------------------------------------------------------
BS_RATIOS = [
    ("bs_3070_vis_45", 0.30, 0.70),
    ("bs_7030_vis_45", 0.70, 0.30),
    ("bs_4060_vis_45", 0.40, 0.60),
    ("bs_6040_vis_45", 0.60, 0.40),
    ("bs_9010_vis_45", 0.90, 0.10),
    ("bs_1090_vis_45", 0.10, 0.90),
]


def gen_bs_ratio_family():
    src = read_table(COATING_TABLES / "bs_5050_vis_45.mietab")
    src = [{k: float(v) for k, v in row.items()} for row in src]
    # sanity: confirm the source table's own d0 relation holds (documents
    # the assumption the construction above relies on)
    for row in src:
        d_r = row["Rs"] - row["Rp"]
        d_t = row["Ts"] - row["Tp"]
        assert abs(d_r + d_t) < 1e-9, "bs_5050_vis_45 source no longer has " \
            "Rs-Rp == -(Ts-Tp); gen_bs_ratio_family()'s construction needs " \
            "updating"

    coating_rows = []
    changed = []
    for name, rR, rT in BS_RATIOS:
        out_rows = []
        for row in src:
            lam = row["wavelength_nm"]
            Ravg = (row["Rs"] + row["Rp"]) / 2.0
            Tavg = (row["Ts"] + row["Tp"]) / 2.0
            total = Ravg + Tavg
            Ravg_new = rR * total
            Tavg_new = rT * total
            d0 = row["Rs"] - row["Rp"]
            d_new = d0 * 4.0 * rR * rT
            Rs = Ravg_new + d_new / 2.0
            Rp = Ravg_new - d_new / 2.0
            Ts = Tavg_new - d_new / 2.0
            Tp = Tavg_new + d_new / 2.0
            out_rows.append((lam, Rs, Rp, Ts, Tp))
        table_path = COATING_TABLES / (name + ".mietab")
        if write_table(table_path, ("wavelength_nm", "Rs", "Rp", "Ts", "Tp"),
                       out_rows):
            changed.append(table_path.name)
        pct_r = int(round(rR * 100))
        pct_t = int(round(rT * 100))
        ref = ('%s: scaled from bs_5050_vis_45 (ratio %d:%d) -- each '
               'wavelength row keeps Rs+Ts == Rp+Tp == the source row\'s '
               'total (R+T), and the source\'s s/p asymmetry style '
               '(Rs-Rp == -(Ts-Tp)) scaled by 4*rR*rT so it stays in '
               '[0,1] at extreme ratios; illustrative, not a vendor part'
               % (GEN_TAG, pct_r, pct_t))
        coating_rows.append({
            "name": name, "layers": "", "table": name + ".mietab",
            "aoi_deg": "45", "reference": ref,
        })
    return coating_rows, changed


# ---------------------------------------------------------------------------
# 2) pellicle rows: flat across the visible, same grid as bs_5050_vis_45
# ---------------------------------------------------------------------------
def gen_pellicle_rows():
    src = read_table(COATING_TABLES / "bs_5050_vis_45.mietab")
    grid = [float(row["wavelength_nm"]) for row in src]

    specs = [
        ("pellicle_4555_45", 0.45, 0.55, 0.99,
         "modeled on a coated pellicle beamsplitter (e.g. Thorlabs/Edmund "
         "45deg pellicle BS lines): thin (~2 micron) nitrocellulose/UV-cure "
         "polymer membrane, negligible dispersion over the visible, flat "
         "R:T=45:55 with ~1% total absorption (typical for a coated "
         "pellicle); illustrative flat approximation, not a digitized "
         "vendor curve"),
        ("pellicle_uncoated_45", 0.08, 0.92, 0.99,
         "modeled on an UNCOATED pellicle membrane at 45deg AOI: flat "
         "R~8%:T~92% (single thin-film Fresnel reflectance of the bare "
         "polymer membrane, no dielectric enhancement coating) with ~1% "
         "total absorption; illustrative flat approximation, not a "
         "digitized vendor curve"),
    ]
    coating_rows = []
    changed = []
    for name, rR, rT, total, basis in specs:
        R = rR * total
        T = rT * total
        out_rows = [(lam, R, R, T, T) for lam in grid]
        table_path = COATING_TABLES / (name + ".mietab")
        if write_table(table_path, ("wavelength_nm", "Rs", "Rp", "Ts", "Tp"),
                       out_rows):
            changed.append(table_path.name)
        ref = "%s: %s" % (GEN_TAG, basis)
        coating_rows.append({
            "name": name, "layers": "", "table": name + ".mietab",
            "aoi_deg": "45", "reference": ref,
        })
    return coating_rows, changed


# ---------------------------------------------------------------------------
# 3) reflective ND (metallic partial reflector), 0 deg AOI, 400-1100nm
#    T = 10^-OD flat; A = 0.25*(1-T) metallic absorption; R = 1 - T - A
# ---------------------------------------------------------------------------
ND_REFL_GRID_NM = [400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900,
                   950, 1000, 1050, 1100]

ND_REFL_ODS = [
    ("nd_refl_od03", 0.3),
    ("nd_refl_od06", 0.6),
    ("nd_refl_od10", 1.0),
    ("nd_refl_od20", 2.0),
    ("nd_refl_od30", 3.0),
]


def gen_nd_refl_rows():
    coating_rows = []
    changed = []
    for name, od in ND_REFL_ODS:
        T = 10.0 ** (-od)
        A = 0.25 * (1.0 - T)
        R = 1.0 - T - A
        out_rows = [(lam, R, R, T, T) for lam in ND_REFL_GRID_NM]
        table_path = COATING_TABLES / (name + ".mietab")
        if write_table(table_path, ("wavelength_nm", "Rs", "Rp", "Ts", "Tp"),
                       out_rows):
            changed.append(table_path.name)
        ref = ("%s: illustrative Inconel-style metallic neutral-density "
               "reflector, flat 400-1100nm at 0deg AOI, OD%.1f "
               "(T=10^-OD=%.6g); metallic absorption modeled as "
               "A=0.25*(1-T) (approximates the typical partial-absorption "
               "fraction of a thin absorbing-metal ND mirror coating, e.g. "
               "Inconel/chromium), R=1-T-A, Rs=Rp and Ts=Tp (non-polarizing "
               "at normal incidence); not a digitized vendor curve"
               % (GEN_TAG, od, T))
        coating_rows.append({
            "name": name, "layers": "", "table": name + ".mietab",
            "aoi_deg": "0", "reference": ref,
        })
    return coating_rows, changed


# ---------------------------------------------------------------------------
# 4) absorptive ND filter family (filters registry): flat internal
#    transmittance T = 10^-OD at ref_thickness_mm = 2.0, 400-1100nm
# ---------------------------------------------------------------------------
ND_FILTER_GRID_NM = [400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900,
                     950, 1000, 1050, 1100]

ND_FILTER_ODS = [
    ("nd_od01", 0.1), ("nd_od02", 0.2), ("nd_od03", 0.3), ("nd_od04", 0.4),
    ("nd_od05", 0.5), ("nd_od06", 0.6), ("nd_od10", 1.0), ("nd_od13", 1.3),
    ("nd_od20", 2.0), ("nd_od30", 3.0), ("nd_od40", 4.0),
]


def gen_nd_filter_rows():
    filter_rows = []
    changed = []
    for name, od in ND_FILTER_ODS:
        T = 10.0 ** (-od)
        out_rows = [(lam, T) for lam in ND_FILTER_GRID_NM]
        table_path = FILTER_TABLES / (name + ".mietab")
        if write_table(table_path, ("wavelength_nm", "transmittance_internal"),
                       out_rows):
            changed.append(table_path.name)
        ref = ("%s: illustrative absorptive Schott-NG-style neutral density "
               "filter, flat internal transmittance 400-1100nm, "
               "T=10^-OD=%.6g at OD%.1f, ref_thickness_mm=2.0 (catalog ND "
               "step); Beer-Lambert thickness scaling per optprops.py's "
               "load_filters(); not a digitized vendor curve"
               % (GEN_TAG, T, od))
        filter_rows.append({
            "name": name, "table_csv": name + ".mietab",
            "ref_thickness_mm": "2.0", "reference": ref,
        })
    return filter_rows, changed


# ---------------------------------------------------------------------------
# 5) shortpass_600: exact mirror of longpass_600's edge about 600nm,
#    T_shortpass(lambda) = T_longpass(1200 - lambda), domain clipped to
#    lambda >= 400nm (mirrors of the 900/1000/1100nm plateau rows fall
#    below 400nm and are dropped).
# ---------------------------------------------------------------------------
def gen_shortpass_row():
    src = read_table(FILTER_TABLES / "longpass_600.mietab")
    pts = []
    for row in src:
        lam = float(row["wavelength_nm"])
        T = float(row["transmittance_internal"])
        mirrored = 1200.0 - lam
        if mirrored >= 400.0:
            pts.append((mirrored, T))
    pts.sort(key=lambda t: t[0])
    table_path = FILTER_TABLES / "shortpass_600.mietab"
    changed = []
    if write_table(table_path, ("wavelength_nm", "transmittance_internal"),
                   pts):
        changed.append(table_path.name)
    ref = ("%s: exact mirror of longpass_600 about 600nm "
           "(T_shortpass(lambda) = T_longpass(1200-lambda)), domain clipped "
           "to >=400nm; same underlying colored-glass sigmoid edge "
           "approximation as longpass_600 (see that row's reference for the "
           "FGL590/FGL610 basis it was interpolated between), reflected to "
           "produce a shortpass cut-off at 600nm; illustrative, not a "
           "vendor part" % GEN_TAG)
    row = {"name": "shortpass_600", "table_csv": "shortpass_600.mietab",
           "ref_thickness_mm": "2.0", "reference": ref}
    return [row], changed


# ---------------------------------------------------------------------------
# 6) notch_633_25: OD4 (T=1e-4) Gaussian notch, FWHM=25nm, centered 633nm,
#    T -> 0.9 outside the notch (same Gaussian-FWHM parametrization bp_550_40
#    uses for its passband: T(x) = Tout - (Tout-Tfloor)*exp(-4*ln2*(x/FWHM)^2))
# ---------------------------------------------------------------------------
NOTCH_CENTER_NM = 633.0
NOTCH_FWHM_NM = 25.0
NOTCH_T_OUT = 0.9
NOTCH_T_FLOOR = 1e-4
NOTCH_OFFSETS_NM = [-233, -100, -50, -30, -20, -15, -12.5, -10, -7, -4, -2,
                    0, 2, 4, 7, 10, 12.5, 15, 20, 30, 50, 100, 200, 300, 400,
                    467]


def _notch_T(x):
    depth = (NOTCH_T_OUT - NOTCH_T_FLOOR) \
        * math.exp(-4.0 * math.log(2.0) * (x / NOTCH_FWHM_NM) ** 2)
    return NOTCH_T_OUT - depth


def gen_notch_row():
    pts = []
    for off in NOTCH_OFFSETS_NM:
        lam = NOTCH_CENTER_NM + off
        pts.append((lam, _notch_T(off)))
    pts.sort(key=lambda t: t[0])
    table_path = FILTER_TABLES / "notch_633_25.mietab"
    changed = []
    if write_table(table_path, ("wavelength_nm", "transmittance_internal"),
                   pts):
        changed.append(table_path.name)
    ref = ("%s: synthetic OD4 (T=1e-4) notch/rejection filter centered at "
           "633nm (e.g. HeNe-line blocking), 25nm-FWHM Gaussian blocking "
           "band T(x)=Tout-(Tout-Tfloor)*exp(-4*ln2*(x/FWHM)^2) -- the same "
           "Gaussian-FWHM parametrization bp_550_40 uses for its passband, "
           "here inverted into a notch -- T~0.9 outside the notch; "
           "illustrative, not tied to a specific vendor part" % GEN_TAG)
    row = {"name": "notch_633_25", "table_csv": "notch_633_25.mietab",
           "ref_thickness_mm": "2.0", "reference": ref}
    return [row], changed


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main():
    coating_rows = []
    table_changes = []
    filter_rows = []

    for gen in (gen_bs_ratio_family, gen_pellicle_rows, gen_nd_refl_rows):
        rows, changed = gen()
        coating_rows.extend(rows)
        table_changes.extend(changed)

    for gen in (gen_nd_filter_rows, gen_shortpass_row, gen_notch_row):
        rows, changed = gen()
        filter_rows.extend(rows)
        table_changes.extend(changed)

    coatings_changed = upsert_registry(COATINGS_CSV, coating_rows)
    filters_changed = upsert_registry(FILTERS_CSV, filter_rows)

    print("tables written/updated: %d" % len(table_changes))
    for c in table_changes:
        print("  %s" % c)
    print("coatings.miecoat changed: %s (%d rows upserted)"
          % (coatings_changed, len(coating_rows)))
    print("filters.miefilt changed:  %s (%d rows upserted)"
          % (filters_changed, len(filter_rows)))


if __name__ == "__main__":
    main()
